// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdministrativeDistrict: typeof import('./src/components/administrativeDistrict.vue')['default']
    Card: typeof import('./src/components/card.vue')['default']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Map: typeof import('./src/components/map.vue')['default']
    Menu: typeof import('./src/components/menu.vue')['default']
    SchoolList: typeof import('./src/components/schoolList.vue')['default']
    SchoolStage: typeof import('./src/components/schoolStage.vue')['default']
  }
}
